<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ContentFiles Include="../../content/**" />
  </ItemGroup>

  <Target Name="CopyContent" BeforeTargets="Build">
    <Copy SourceFiles="@(ContentFiles)" DestinationFolder="$(OutDir)content/%(RecursiveDir)" />
  </Target>

</Project>
